### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку virt_mem_max Абрамов Иван

### ISSUE THREAD

**Issue by AirVan21** [AirVan21/au-linux-kernel-spring-2016#3]
[Commit](https://github.com/AirVan21/au-linux-kernel-spring-2016/commit/c28e08655a8b95899165f7ab6dcb8820637b3918)

**Comment by eabatalov** [comment]
The idea is right. But you should had used mmap instead of malloc. Then solution would work very well.

**Comment by eabatalov** [comment]
75 points out of 100.

**Comment by eabatalov** [comment]
Ok. Thank you for you initiative to fix your score.
On my system malloc solution works 0.955 sec and mmap solution works 0.024 sec.
100 out of 100 points.

**Comment by AirVan21** [comment]
Thank you for checking this code one more time. 
It seems, that now we've got an examined advantage of mmap against malloc)
